### ISSUE TITLE
support prediction (CPU) by using the training model based on Cuml

### ISSUE THREAD

**Issue by LIUZhaohan0** [DataCanvasIO/Hypernets#62]

**Comment by beckernick** [comment]
Hi! I just came across this project and it looks great.

I wanted to mention that we've implemented input-to-output data type consistency for cuML estimators. This means that while training and prediction will be on the GPU, if you pass CPU data into the estimator it will return CPU data from `estimator.predict` or `predict_proba`.

Happy to help answer questions about cuML (or cuDF) if you have any.

**Comment by lixfz** [comment]
@beckernick Thank you for your comment.

Our project is a full pipeline optimization framework,  we hope the trained pipeline can run `predict` and `predict_proba` without GPUs, including the transformers and the estimators. On the other hand, we hope to run prediction without the cuml/cudf, because the deployments of cuda/cudf/cuml are too heavy for some environments.

We found the cuml document about [exporting estimator for inferencing on machines without GPUs](https://docs.rapids.ai/api/cuml/stable/pickling_cuml_models.html#Exporting-cuML-Random-Forest-models-for-inferencing-on-machines-without-GPUs), but we didn't find similar information about exporting the trained transfomers. So we think we need do something to do that.

**Comment by beckernick** [comment]
Thanks for the concrete request. I'll file an issue on cuML to track this request and cross-link this issue

**Comment by lixfz** [comment]
We adapt hypernts and hypergbm to deploy the trained estimator with .as_local() method, see example [HyperGBM GUP acceleration](https://hypergbm.readthedocs.io/en/latest/example_cuml.html) .
